apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-nrf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-nrf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-nrf
    spec:
      containers:      
      - name: free5gc-nrf
        image: free5gc:2.0
        securityContext:
          privileged: true        
        command: ["/bin/sh"]
        args: ["-c", "/free5gc/bin/nrf "]
        volumeMounts:
        - name: nrfcfg
          mountPath: /free5gc/config/nrfcfg.yaml
          subPath: nrfcfg.yaml
        ports:
        - containerPort: 30001
          name: f5gc-nrf
          protocol: TCP
      volumes:
      - name: nrfcfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: nrfcfg.yaml
            path: nrfcfg.yaml
      
---
apiVersion: v1
kind: Service
metadata:
  name: free5gc-nrf-svc
spec:
  type: NodePort
  ports:
  - port: 30001
    nodePort: 30001
  selector:
    app: free5gc-nrf
---