{
 "title": "网元功能单元监控可视化",
 "description": "cadvisor:v0.32.0",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "网元名称",
    "query": {
     "query": "label_values(container_last_seen, container_label_io_kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# 5G核心网网元功能单元监控可视化\n\n           "
   }
  },
  {
   "title": "正常运行中的网元",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{container_label_io_kubernetes_pod_name=~\"$project\", image!=\"docker.io/rancher/pause:3.1\"})"
    }
   ]
  },
  {
   "title": "总消耗内存",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$project\", image!=\"docker.io/rancher/pause:3.1\"})/1024/1024"
    }
   ]
  },
  {
   "title": "CPU利用率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{container_label_io_kubernetes_pod_name=~\"$project\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU利用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container_label_io_kubernetes_pod_name=~\"$project\", image!=\"docker.io/rancher/pause:3.1\"}[5m]) * 100",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "内存利用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"$project\", image!=\"docker.io/rancher/pause:3.1\"}",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "接收报文总数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{container_label_io_kubernetes_pod_name=~\"$project\",image!=\"\"}[5m])",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "发送报文总数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{container_label_io_kubernetes_pod_name=~\"$project\",image!=\"\"}[5m])",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "I/O Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{container_label_io_kubernetes_pod_name=~\"$project\"}[5m])",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "I/O Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_writes_bytes_total{container_label_io_kubernetes_pod_name=~\"$project\", image!=\"docker.io/rancher/pause:3.1\"}[5m])",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  }
 ]
}